### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/tomgurion.me#1]

**Comment by d2s** [comment]
Just looking at the site files (to learn more of how people use Python).
- `.env` and `.out` files are most likely for zsh [autoenv](https://github.com/horosgrisa/autoenv) that you have contributed to.
- What tool is used to install dependencies from `environment.yml` file?

**Comment by Nagasaki45** [comment]
@d2s, thanks for your interest!
- The `.env` and `.out` files are for autoenv indeed. I'm using [horosgrisa/autoenv](https://github.com/horosgrisa/autoenv) with zsh but there are lots of other autoenv tools (e.g. [kennethreitz/autoenv](https://github.com/kennethreitz/autoenv)). The idea behind these tools is to prepare the environment of the project when you `cd` into it.
- Most of the python community use pip and virtualenv to manage dependencies per project. Lately, I prefer to use [conda](http://conda.pydata.org/docs/) as a replacement for both tools. The main reason is that there are many scientific packages that are not installable with pip but easily managed by conda. Another reason is that with conda I have a "root" environment, which is not the system wide environment, for making changes and try different things. You will never ruin your system wide python installation this way. Last thing, you can create environment with any version of python, not only with the versions that available in your system. Most of the reasons above are almost irrelevant for this project, but I always try to choose the most capable tools for my toolbox and work with them.

If you have more questions feel free to contact me directly: nagasaki45@gmail.com.
